"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Links from '@/components/Links'
import Navbar from '@/components/Navbar'
import LinksMobile from '@/components/LinksMobile'
import { useState } from 'react'
import MobileToggle from '@/components/MobileToggle '




const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Dashboard Pouria',
//   description: 'Generated by create next app',
// }




export default function RootLayout({ children }) {


  const [mobileLinksShow, setMobileLinksShow] = useState(false);


  return (
    <html lang="en">

      <body className={inter.className}>
        <span className='md:hidden' onClick={() => { setMobileLinksShow(!mobileLinksShow) }}>
          <MobileToggle />
        </span>
        <div className={`trans-all ${mobileLinksShow ? '' : 'hidden'}`}>
          <LinksMobile />
        </div>
        <section className='p-4 min-h-screen leading-loose'>
          <div className="row bg-transparent-3 rounded-3xl min-h-95">
            <div className="col-md-2 py-3 hidden md:block">
              <h2 className='text-2xl mb-12 mt-5 p-3' >
                Admin Panel
              </h2>
              <div className='hidden md:block'>
                <Links />
              </div>
            </div>
            <div className="col-md-10 p-3">
              <Navbar />
              <div className='p-4'>
                {children}
              </div>
            </div>

          </div>
        </section>
      </body>
    </html>
  )
}
